// <auto-generated />
using System;
using ConsumerDebit.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsumerDebit.Migrations
{
    [DbContext(typeof(ConsumerDebitDbContext))]
    [Migration("20220214013234_AllUsersMigration")]
    partial class AllUsersMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ConsumerDebit.Model.Traffic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Claims")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<int>("Owes")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Traffics");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Claims = 0,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document = "Početno stanje",
                            Owes = 580,
                            UserId = "S00001"
                        },
                        new
                        {
                            ID = 2,
                            Claims = 581,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document = "Početno stanje",
                            Owes = 0,
                            UserId = "S00002"
                        },
                        new
                        {
                            ID = 3,
                            Claims = 0,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document = "Početno stanje",
                            Owes = 1154,
                            UserId = "S00003"
                        },
                        new
                        {
                            ID = 4,
                            Claims = 0,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document = "Zaduzenje",
                            Owes = 200,
                            UserId = "S00001"
                        },
                        new
                        {
                            ID = 5,
                            Claims = 0,
                            Date = new DateTime(2021, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Document = "Zaduzenje",
                            Owes = 180,
                            UserId = "S00001"
                        });
                });

            modelBuilder.Entity("ConsumerDebit.Model.User", b =>
                {
                    b.Property<string>("IDUser")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("IDUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IDUser = "S00001",
                            Owner = "Novakovic Petar",
                            Password = "317D"
                        },
                        new
                        {
                            IDUser = "S00002",
                            Owner = "Miloševic Dragan",
                            Password = "EFFC"
                        },
                        new
                        {
                            IDUser = "S00003",
                            Owner = "Bardak Željko",
                            Password = "5110"
                        },
                        new
                        {
                            IDUser = "S00004",
                            Owner = "Gligoric Svetislav",
                            Password = "B522"
                        },
                        new
                        {
                            IDUser = "S00005",
                            Owner = "Vukovic Mirjana",
                            Password = "A290"
                        },
                        new
                        {
                            IDUser = "S00006",
                            Owner = "Nikolic Dragan",
                            Password = "3000"
                        },
                        new
                        {
                            IDUser = "S00007",
                            Owner = "Dedouh Dragutin",
                            Password = "A662"
                        },
                        new
                        {
                            IDUser = "S00008",
                            Owner = "Petruš Ornela",
                            Password = "A590"
                        },
                        new
                        {
                            IDUser = "S00009",
                            Owner = "Filipovic Ljiljana",
                            Password = "EE7F"
                        },
                        new
                        {
                            IDUser = "S00010",
                            Owner = "Borojevic Boris",
                            Password = "CB60"
                        },
                        new
                        {
                            IDUser = "S00011",
                            Owner = "Žebeljanovic Zoran",
                            Password = "6D0D"
                        },
                        new
                        {
                            IDUser = "S00012",
                            Owner = "Vujanic Ivkov Gordana",
                            Password = "17ED"
                        },
                        new
                        {
                            IDUser = "S00013",
                            Owner = "Andric Gavrilovic Dragan",
                            Password = "092B"
                        },
                        new
                        {
                            IDUser = "S00014",
                            Owner = "Kostic Miloš",
                            Password = "3CD3"
                        },
                        new
                        {
                            IDUser = "S00015",
                            Owner = "Lukićević Srbislava",
                            Password = "67EC"
                        },
                        new
                        {
                            IDUser = "S00016",
                            Owner = "Ilic Danka",
                            Password = "B045"
                        },
                        new
                        {
                            IDUser = "S00017",
                            Owner = "Tešinovic Pero",
                            Password = "31B5"
                        },
                        new
                        {
                            IDUser = "S00018",
                            Owner = "Vejinovic Mirko",
                            Password = "61EE"
                        });
                });

            modelBuilder.Entity("ConsumerDebit.Model.Traffic", b =>
                {
                    b.HasOne("ConsumerDebit.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
