// <auto-generated />
using ConsumerDebit.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConsumerDebit.Migrations
{
    [DbContext(typeof(ConsumerDebitDbContext))]
    partial class ConsumerDebitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ConsumerDebit.Model.User", b =>
                {
                    b.Property<string>("IDUser")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("IDUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IDUser = "S00001",
                            Owner = "Novakovic Petar",
                            Password = "317D"
                        },
                        new
                        {
                            IDUser = "S00002",
                            Owner = "Miloševic Dragan",
                            Password = "EFFC"
                        },
                        new
                        {
                            IDUser = "S00003",
                            Owner = "Bardak Željko",
                            Password = "5110"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
